### ISSUE TITLE
not linking files

### ISSUE THREAD

**Issue by l3lack-eyes** [EverythingSuckz/TG-FileStreamBot#120]
hello . 
i've deployed bot recently using docker compose and it responds to my /start bot not linking my files.

**Comment by EverythingSuckz** [comment]
@l3lack-eyes You sure that you've filled out the env vars? If possible, can you share the logs?

**Comment by l3lack-eyes** [comment]
yes vars are filled . how to see logs?

**Comment by DeekshithSH** [comment]
Added Bot as Admin in Bin Channel?

**Comment by l3lack-eyes** [comment]
oh . I did it now and it's working . thanks D:

**Comment by l3lack-eyes** [comment]
the given link are like this http://0.0.0.0:8080/f65b9d4 why it is not my server's ip address and myselected port was 8000 which in the link is 8080

**Comment by l3lack-eyes** [comment]
version: "3.8"

services:
fsb:
build: .
restart: unless-stopped
container_name: fsb
environment:
# required
- API_ID=28077### # change this to your ID
- API_HASH=e84821a2cb2###eba1b8334947ca### # change this to your HASH
- BOT_TOKEN=6##https://github.com/EverythingSuckz/TG-FileStreamBot/pull/6958:AAEowfXEFUkPdIA51##DEQql-bN75ZE_FE # enter you> - BIN_CHANNEL=-1001##5193##6 # paste channel ID
ports:
- 127.0.0.1:8000:8000
volumes:
- $HOME/TG-FileStreamBot:/app/.env
       - port=8000
       - fqdn=##.###ivr.link
is this right?it didn't work for me . port 8000 is open

**Comment by EverythingSuckz** [comment]
> is this right?it didn't work for me . port 8000 is open

No the configuration is wrong.

```yml
version: "3.8"

services:
fsb:
build: .
restart: unless-stopped
container_name: fsb
environment:
- API_ID=28077XXXX
- API_HASH=e84821a2cb2XXXXXXXXXX
- BOT_TOKEN=XXXXXXX
- BIN_CHANNEL=-100XXXXXXXX
- PORT = 8080
- FQDN = 192.165.15.1 #(Your server IP or domain without protocol)
ports:
- 127.0.0.1:8000:8000
```
