### ISSUE TITLE
Unable to access the provided link.

### ISSUE THREAD

**Issue by stunzz** [EverythingSuckz/TG-FileStreamBot#133]
I used docker-compose.yml to install the bot. Everything worked as expected. Forwarded a file to the bot, it gave me a link; which is **inaccessible**. I am providing you my yml file. Please help.

```
version: "3.5"

services:
  fsb:
    build: .
    restart: unless-stopped
    container_name: fsb
    environment:
      - API_ID=218XXXXX
      - API_HASH=5e734e8fbc0dc811bXXXXXXXXXX
      - BOT_TOKEN=6486062146:AAGIqXXXXXXXXXXXX
      - BIN_CHANNEL=-1002143533691
      - PORT=8086
      - FQDN=182.250.188.172
    ports:
      - "172.17.0.1:8086:8000"
```
On the browser it says **Site is not reachable**.
